### ISSUE TITLE
Missing GUI Elements when using the theme

### ISSUE THREAD

**Issue by ar0ra1** [btd1337/eOS-Sierra-Gtk#1]
Arc Theme - 
![arc](https://user-images.githubusercontent.com/20777462/31796812-e60c9734-b548-11e7-8366-aea01eb67e51.png)

Sierra Theme - 
![sierra](https://user-images.githubusercontent.com/20777462/31796837-f1d7eb86-b548-11e7-9d7e-0504cf1700ce.png)

It occurs at various other places too.

**Comment by ar0ra1** [comment]
@btd1337 
I think i found the temporary solution out
I need you to post screenshot of
screenshot-tool, terminal and application menu

**Comment by btd1337** [comment]
Don't understand. 

Does it have to be from my system? Why?

**Comment by ar0ra1** [comment]
you made.
just need to verify my changes.

**Comment by btd1337** [comment]
Unfortunately my elementary OS has a boot problem. I have been using Arch until I have time to resolve it.

if possible create a folder with the original project and another with its modifications. See if it solved.

**Comment by ar0ra1** [comment]
Okay!
The thing i noticed with GtkInspector is that the dark variant was being forcefully active even when not needed.
So, i basically removed the dark variant files.
Viola, 
It started working. There are still few minor bugs
Like in the screenshots you have displayed
There is a tick icon in file browser indicating the selected folder
but i don't get that 
unless i open the Files (as root; weird)

Few Other changes i made to the theme, 
made text white, because the selected item background color is in blue-ish/purple tone
and the text was in black

Few more bugs remain,
let me know when you have your eOS up and running 
I would like to know few things about GtkInspector and hopefully fix all the bugs for you :)

**Comment by ar0ra1** [comment]
Also, I made a plank theme for it,
Similar color scheme like in the screenshot (Cairo Dock)
I'll post that too :)

**Comment by btd1337** [comment]
Nice job! 
Please, test this changes and send a pull request.

**Comment by btd1337** [comment]
@ar0ra1 do you have any news?

**Comment by ar0ra1** [comment]
@btd1337 
You can fork the plank theme from my profile.

So, for testing purpose regarding the dark theme. I checked on 4 different PCs, the screenshot bug is still present.
To overcome that, all you need to do is remove the `dark css files`

- granite-widgets-dark.css
- gtk-widgets-dark.css
- gtk-widgets-dark.css

Rest of the few changes I made as a personal preference to the color scheme. Nothing major, apart from that, I tried to change the label color but it has a direct impact on some applications and it also varies from background color to color.  
I think i made some changes to GtkTreeView label, I'm gonna put a pull request, do a comparison and let you know about all the changes.

**Comment by btd1337** [comment]
**_Issue fixed in the commit https://github.com/btd1337/eOS-Sierra-Gtk/commit/a55165ae4f11ead5b8dbf7209495a2d30390a656_**

**Comment by ar0ra1** [comment]
@btd1337  
try the plank theme 
https://ar0ra1.github.io/plank-theme/
