### ISSUE TITLE
Problema com Google Chrome

### ISSUE THREAD

**Issue by Jovennan** [btd1337/eOS-Sierra-Gtk#2]
Ao maximizar a janela do google chrome, os botões de controle da janela(minimizar, maximizar e fechar) ficam destorcidos.

**Comment by caobach42** [comment]
![image](https://user-images.githubusercontent.com/38379440/38769343-8afac4d8-402b-11e8-9bdb-a80d24a4c30d.png)

same problem on elementary OS 0.4.1 Loki with Chrome v.65.0.3325.181

**Comment by Jovennan** [comment]
Problema parcialmente resolvido na 

![screenshot from 2018-05-16 10 00 46](https://user-images.githubusercontent.com/1591954/40121164-5297a176-58f7-11e8-9c67-51b0cf63aa6e.png)

Version 67.0.3396.40 (Official Build) beta (64-bit)
